### ISSUE TITLE
Userscripts disappeared 

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#15]
After updating to non standard header and setting up adaway all of my Userscripts have disappeared and I can't install new Userscripts it doesn't show anything in the front end when i install them

**Comment by MohamadBayz** [comment]
Also adaway doesn't block anything i think it had something to do with this

**Comment by JingMatrix** [comment]
I get it, I updated he datebase code to reduce app size, so normally it cause bugs.

Could you use it and do something related to userscripts in Chrome so that you can produce some useful log in Xposed?
Then you post it here so I can analyze.
Currently, it works fine in my phone, so I cannot reproduce it by myself.

**Comment by JingMatrix** [comment]
Now the bug is fixed, hope your data didn't get destroyed by that bug.

**Comment by JingMatrix** [comment]
Should be fixed now.

**Comment by MohamadBayz** [comment]
Even with the latest version it's still not showing in the lsposed log it says failed to hook should i send the log?

**Comment by JingMatrix** [comment]
Yeah, paste it here please.

**Comment by MohamadBayz** [comment]
Here's the module log
https://pastebin.com/raw/00h96R91
And this is the verbose log
https://pastebin.com/raw/QLrZ6VAe

**Comment by MohamadBayz** [comment]
Here's the entire log
https://anonfiles.com/U2C0edPdy9/LSPosed_2022-12-29T12_51_23.807_zip

**Comment by JingMatrix** [comment]
The Log didn't show anything wrong with my app.
It contains almost no item about ChromeXt.

Please clear old logs and interact with chrome to try triger the bugs: installing some new scripts, use the front end or so on.

**Comment by MohamadBayz** [comment]
In the verbose it says hook failed 
I'll try to get new log

**Comment by MohamadBayz** [comment]
Is this helpful
`----part 2 start----
[ 2022-12-29T16:11:11.824        0:   651:  1157 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-12-29T16:11:11.824.log
[ 2022-12-29T16:11:13.662        0:   651:  1087 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-12-29T16:11:13.664        0:   651:  1157 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-12-29T16:11:13.663.log
[ 2022-12-29T16:11:28.422    10459: 26370: 26370 I/LSPosed         ] Loading xposed for org.matrix.chromext/10459
[ 2022-12-29T16:11:28.427    10459: 26370: 26370 I/LSPosed-Bridge  ] Loading module org.matrix.chromext from /data/app/~~MZaVG5kmOWIZw1-FJBRYDQ==/org.matrix.chromext-CTPADx8Qy_ALhEYqdQpyCw==/base.apk
[ 2022-12-29T16:11:28.429    10459: 26370: 26370 I/LSPosed-Bridge  ]   Loading class org.matrix.chromext.MainHook
[ 2022-12-29T16:11:28.837    10135: 21732: 21732 I/LSPosed-Bridge  ] java.lang.NullPointerException
[ 2022-12-29T16:11:31.133    10135: 21732: 21732 I/LSPosed-Bridge  ] java.lang.NullPointerException
[ 2022-12-29T16:11:32.604    10135: 21732: 21732 I/LSPosed-Bridge  ] java.lang.NullPointerException
`

**Comment by JingMatrix** [comment]
Yeah seems, please show me what after this NullPointerException

**Comment by JingMatrix** [comment]
It might be possible that your userscript database is destroyed.
In this unfornate case, clear the data of you Chrome app should make everything work again, but surely you lost your userscript data.

**Comment by MohamadBayz** [comment]
That was the end of the lof here's a new one where i tried to install a new Userscript
`----part 4 start----
[ 2022-12-29T17:07:05.261        0:   646:  1191 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-12-29T17:07:05.26.log
[ 2022-12-29T17:07:09.215    10135: 19019: 19019 E/LSPlant         ] Hook Fails: _ZN3art11ClassLinker26VisiblyInitializedCallback29AdjustThreadVisibilityCounterEPNS_6ThreadEl
[ 2022-12-29T17:07:09.236    10135: 19019: 19019 I/LSPosed         ] Loading xposed for com.android.chrome/10135
[ 2022-12-29T17:07:09.245    10135: 19019: 19019 I/LSPosed-Bridge  ] Loading module org.matrix.chromext from /data/app/~~MZaVG5kmOWIZw1-FJBRYDQ==/org.matrix.chromext-CTPADx8Qy_ALhEYqdQpyCw==/base.apk
[ 2022-12-29T17:07:09.249    10135: 19019: 19019 I/LSPosed-Bridge  ]   Loading class org.matrix.chromext.MainHook
[ 2022-12-29T17:07:10.279    10135: 19112: 19112 E/LSPlant         ] Hook Fails: _ZN3art11ClassLinker26VisiblyInitializedCallback29AdjustThreadVisibilityCounterEPNS_6ThreadEl
[ 2022-12-29T17:07:10.291    10135: 19112: 19112 I/LSPosed         ] Loading xposed for com.android.chrome:privileged_process0/10135
[ 2022-12-29T17:07:10.299    10135: 19112: 19112 I/LSPosed-Bridge  ] Loading module org.matrix.chromext from /data/app/~~MZaVG5kmOWIZw1-FJBRYDQ==/org.matrix.chromext-CTPADx8Qy_ALhEYqdQpyCw==/base.apk
[ 2022-12-29T17:07:10.302    10135: 19112: 19112 I/LSPosed-Bridge  ]   Loading class org.matrix.chromext.MainHook
[ 2022-12-29T17:07:29.387    10135: 19019: 19019 I/LSPosed-Bridge  ] android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=12, totalRows=13
[ 2022-12-29T17:07:55.090    10135: 19019: 19019 I/LSPosed-Bridge  ] android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=12, totalRows=13
`

**Comment by JingMatrix** [comment]
Since it says `SQLiteBlobTooBigException`, mayeb you try to (re-) installed a smaller one to see if ChromeXt is working?

For example, the office cosmetic userscript.

**Comment by JingMatrix** [comment]
Now I have increase the allowed query size to 10M, that should work for you.

**Comment by MohamadBayz** [comment]
as you said that the database was destroyed so I tried clearing Chrome's data to rebuild the database and that fixed the issue

**Comment by JingMatrix** [comment]
Sorry for those bugs introduced by my attempts.
I hope you still enjoy this application.

**Comment by MohamadBayz** [comment]
No big deal, i Still enjoy it
I hope you keep on supporting this project for further future
