### ISSUE TITLE
The Tampermonkey script "Immersive Translate" is not working.

### ISSUE THREAD

**Issue by commiyou** [JingMatrix/ChromeXt#54]
no bubbles of the translate tool was found on the screen 

the project: https://github.com/immersive-translate/immersive-translate

**Comment by JingMatrix** [comment]
The problem of the ChromeXt side is fixed in the latest commit.
Note that there is bug in their official site, https://immersivetranslate.com : their downloaded js files are not encoded as `utf-8`.
Hence, for you to use it correctly:
1. Install ChromeXt from the Github Action
2. Download the script from their [release page](https://github.com/immersive-translate/immersive-translate/releases/), not from the link they provided in the README.

You can choose to report the above bug to them if you want.

**Comment by JingMatrix** [comment]
It is not working on which sites? Can you see its icon on `google.com`?
It cannot be present at `github.com` due to GitHub`s restriction.
Also, the script is not working well; I think the script itself is buggy.

**Comment by Typhonling** [comment]
I guess he is still using the "latest release"  instead of the "latest commit"? For me I'll wait for the next release before I say anything, after all I want to use this script too.

**Comment by JingMatrix** [comment]
It seems the script is interesting for many people.
I will investigate the script deeper to see which part is buggy.
Currently in my Chrome, it works sometimes but also fails sometimes.
It is mysterious as this because the authors deliberately hide the script logs, making it harder to debug.

**Comment by commiyou** [comment]
This script's Tampermonkey version works fine when simulating mobile devices on PC Chrome, but it doesn't show the bubble on mobile Chromext.
<img width="358" alt="image" src="https://github.com/JingMatrix/ChromeXt/assets/5888756/37431d20-cc7c-4833-b45f-64bb395a9791">

**Comment by JingMatrix** [comment]
Sure, I know how it looks when it works.
But could you confirm that you can see this icon on `twitter.com` with ChromeXt?
The question is for debugging purpose; it helps me to analyse the problem.

**Comment by JingMatrix** [comment]
Thanks for tell me that. I am in the same situation.
However, I realised that their script isn't open source at all.
That GitHub repo is only for their docs.
There is no source code for me to debug, I cannot find where the problem is for now.

**Comment by JingMatrix** [comment]
Here is how to make it work:
1. Install latest ChromeXt from the [GitHub Action](https://github.com/JingMatrix/ChromeXt/actions)
2. Install the script from their [release page](https://github.com/immersive-translate/immersive-translate/releases/)
3. Configure this script to run at `Start` from the front-end manager.

If this still fail, I will open this issue again.

**Comment by commiyou** [comment]
Great! it works. Thank you for resolving this issue so quickly!

**Comment by JingMatrix** [comment]
Glad to see that it works.

Here are two notes:
1. Due to limitations of ChromeXt, the setting from the script options page won't apply, this might be improved in the future. This is because ChromeXt doesn't allow tab communication yet.
2. Some page won't be translated, which is due to restriction from the websites. ChromeXt cannot do anything for it for security reason.

**Comment by Typhonling** [comment]
Great progress! Unfortunately, custom translation services are not yet supported. Maybe I should get used to Fennec soon lol.

**Comment by JingMatrix** [comment]
Now the tab communication is implemented, meaning that this script should work as expected.
You can configure its options as you want.

**Comment by Typhonling** [comment]
Thanks for your hard work! In fact, the default translation services work fine (Google, Bing and Tencent), but the custom translation services still don't work. Specifically, "Click on this test service" does not work with any translation service.

**Comment by JingMatrix** [comment]
Thanks for testing, I fixed `Click on this test service` function now.
It should work now.

By the way, now you don't need to change the RunAt to `Start`.

**Comment by Typhonling** [comment]
Sorry, the custom translation service still doesn't work (still only tested DEEPL). When testing it shows "Network request failed". It works properly in both Firefox and KIWI's Tampermonkey in the same environment.

**Comment by JingMatrix** [comment]
I tested it with a new DeepL account. Yes, the problem exists.

It is harder to solve than inter-tab comminucation problem: it reaches the second limitation of ChromeXt mentioned above. So far, I still don't have good solution for it.
In my opinion, as a translate service, DeepL should set this kind of CORS security restriction.

**Comment by Typhonling** [comment]
Thanks again for your work. I don't think it's worth continuing to waste more effort on this script.

**Comment by JingMatrix** [comment]
I have bypassed those connection restrictions.
Now you can use this script on any sites.  And I tested that `DeepL` is working well, at least on `github.com`.

Please test it and report problems if you encounter any.

**Comment by Typhonling** [comment]
Perfect fix. It's incredible, great job!
